language: node_js
node_js:
  - "9"
  - "8"
  - "7"
  - "6"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libzmq3-dev
script:
  - npm test
install:
  - npm install --dev
after_success:
  - bash <(curl -s https://codecov.io/bash)
